# Generated by Django 5.2.5 on 2025-08-29 16:06

import django.db.models.deletion
import django_multitenant.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('diagnosis', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.clinic')),
            ],
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
    ]
