# Generated by Django 5.2.5 on 2025-08-28 17:58

import django_multitenant.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
    ]
