# Generated by Django 5.2.5 on 2025-08-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories_configurations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttype',
            options={'ordering': ['name'], 'verbose_name': 'Tipo de Pago', 'verbose_name_plural': 'Tipos de Pago'},
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='code',
            field=models.CharField(error_messages={'max_length': 'El código no debe superar los 50 caracteres.', 'unique': 'Este código ya existe.'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='name',
            field=models.CharField(error_messages={'max_length': 'El nombre no debe superar los 255 caracteres.', 'unique': 'Este nombre ya existe.'}, max_length=255, unique=True),
        ),
    ]
